_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 10
dropout:
    value: 0.1
emb_size:
    value: 256
epochs:
    value: 2
ff_hidden_mult:
    value: 4
lr:
    value: 0.0001
n_heads:
    value: 4
n_layers:
    value: 4
num_train:
    value: 10
output_dir:
    value: test_run2
seed:
    value: 22
seq_len:
    value: 120
